"""
Logos → C transpiler.

Transforms a Program AST into C source that can be compiled together with
logos_runtime.c to produce a native binary.

Backtracking model: continuation-passing style (CPS).  Each predicate
dispatcher tries all its clauses sequentially, undoing environment changes
between attempts.  Results are communicated through env->capture_found /
env->capture_conf rather than through the return value, so that all proof
paths are explored (OR-aggregation across multiple derivations).
"""

from __future__ import annotations
from typing import Any

from logos.ast_nodes import (
    Program, TypeDecl, SemanticBinding, InferenceRule,
    BoolQuery, FindQuery, PredicateCall, Comparison, NegatedPredicate,
    DurationLit, Variable, Path, SetLit, ListLit, ArithExpr,
    ImportStmt, Retraction, TransformDecl, ContextDecl,
)


class CompilationError(Exception):
    """Raised when a Logos program cannot be compiled to C."""


# Comparison operator → numeric code (matches logos_runtime.c logos_compare)
_OP_MAP: dict[str, int] = {">=": 0, "<=": 1, ">": 2, "<": 3, "=": 4, "!=": 5}


def _c_id(name: str) -> str:
    """Convert a Logos identifier to a valid C identifier fragment."""
    return name.replace("-", "_").replace(".", "_")


def _esc(s: str) -> str:
    """Escape a Python string for embedding in a C string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


# ── Compiler ──────────────────────────────────────────────────────────────────

class Compiler:
    """Transforms a Program AST into a C source string."""

    def __init__(self, program: Program):
        self.program = program
        self.facts:   list[SemanticBinding] = []
        self.rules:   list[InferenceRule]   = []
        self.queries: list[Any]              = []
        # pred_name → list of (clause_index, InferenceRule) in order
        self.rules_by_pred: dict[str, list[tuple[int, InferenceRule]]] = {}

        for stmt in program.statements:
            if isinstance(stmt, SemanticBinding):
                self._check_binding(stmt)
                self.facts.append(stmt)
            elif isinstance(stmt, InferenceRule):
                pred = stmt.head.name
                if pred not in self.rules_by_pred:
                    self.rules_by_pred[pred] = []
                idx = len(self.rules_by_pred[pred])
                self.rules_by_pred[pred].append((idx, stmt))
                self.rules.append(stmt)
            elif isinstance(stmt, (BoolQuery, FindQuery)):
                self.queries.append(stmt)
            elif isinstance(stmt, TypeDecl):
                pass  # silently skipped
            elif isinstance(stmt, ImportStmt):
                raise CompilationError(
                    "import statements are not supported in compiled mode"
                )
            # Retraction / TransformDecl / ContextDecl silently skipped

    # ── Validation ────────────────────────────────────────────────────────────

    def _check_binding(self, b: SemanticBinding) -> None:
        val = b.value
        if isinstance(val, (SetLit, ListLit)):
            raise CompilationError(
                f"SetLit/ListLit fact values are not supported in compiled mode"
                f" (at {b.path})"
            )
        if isinstance(val, ArithExpr):
            raise CompilationError(
                f"ArithExpr fact values are not supported in compiled mode"
                f" (at {b.path})"
            )

    # ── Top-level generation ──────────────────────────────────────────────────

    def generate(self) -> str:
        return "\n".join([
            self._emit_preamble(),
            self._emit_forward_decls(),
            self._emit_rule_functions(),
            self._emit_pred_dispatchers(),
            self._emit_setup(),
            self._emit_main(),
        ])

    # ── Preamble ──────────────────────────────────────────────────────────────

    def _emit_preamble(self) -> str:
        return (
            '/* Generated by Logos compiler — do not edit by hand */\n'
            '#include "logos_runtime.h"\n'
            '#include <stdio.h>\n'
            '#include <string.h>\n'
            '\n'
        )

    # ── Forward declarations ──────────────────────────────────────────────────

    def _emit_forward_decls(self) -> str:
        lines = ["/* Forward declarations */"]
        for pred, clauses in self.rules_by_pred.items():
            first_rule = clauses[0][1]
            param_str = self._pred_param_decl(first_rule)
            lines.append(
                f"static int rule_{_c_id(pred)}_0"
                f"(logos_env *env, {param_str}, logos_cont k);"
            )
            lines.append(
                f"int pred_{_c_id(pred)}"
                f"(logos_env *env, {param_str}, logos_cont k);"
            )
        lines.append("")
        return "\n".join(lines)

    def _pred_param_decl(self, rule: InferenceRule) -> str:
        """C parameter declarations for the rule's head arguments."""
        parts = []
        for arg in rule.head.args:
            parts.append(f"logos_term var_{self._head_arg_cname(arg)}")
        return ", ".join(parts)

    def _pred_param_pass(self, rule: InferenceRule) -> str:
        """C argument list passing the head vars through."""
        parts = []
        for arg in rule.head.args:
            parts.append(f"var_{self._head_arg_cname(arg)}")
        return ", ".join(parts)

    def _head_arg_cname(self, arg: Any) -> str:
        """C name fragment for a rule-head argument (Variable or Path)."""
        if isinstance(arg, Variable):
            return _c_id(arg.name)
        elif isinstance(arg, Path):
            return _c_id(arg.root())
        else:
            return "arg"

    # ── Rule functions ────────────────────────────────────────────────────────

    def _emit_rule_functions(self) -> str:
        parts = []
        for pred, clauses in self.rules_by_pred.items():
            for idx, rule in clauses:
                emitter = RuleEmitter(rule, pred, idx, self)
                parts.append(emitter.emit())
        return "\n".join(parts)

    # ── Predicate dispatchers ─────────────────────────────────────────────────

    def _emit_pred_dispatchers(self) -> str:
        parts = []
        for pred, clauses in self.rules_by_pred.items():
            cname      = _c_id(pred)
            first_rule = clauses[0][1]
            param_decl = self._pred_param_decl(first_rule)
            param_pass = self._pred_param_pass(first_rule)
            lines = [
                f"int pred_{cname}(logos_env *env, {param_decl}, logos_cont k) {{",
            ]
            for idx, _rule in clauses:
                lines.append(f"    {{ logos_mark_t _m = logos_mark(env);")
                lines.append(
                    f"    if (rule_{cname}_{idx}(env, {param_pass}, k))"
                    f" {{ logos_undo(env, _m); return 1; }}"
                )
                lines.append(f"    logos_undo(env, _m); }}")
            lines.append(f"    return 0;")
            lines.append(f"}}")
            lines.append("")
            parts.append("\n".join(lines))
        return "\n".join(parts)

    # ── logos_setup ───────────────────────────────────────────────────────────

    def _emit_setup(self) -> str:
        lines = ["void logos_setup(logos_graph *g) {"]
        for b in self.facts:
            subj, pred = self._decompose_path(b.path)
            val_expr   = self._emit_value(b.value)
            conf       = self._get_confidence(b)
            lines.append(
                f'    logos_graph_assert(g, "{_esc(subj)}", '
                f'"{_esc(pred)}", {val_expr}, {conf});'
            )
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    def _decompose_path(self, path: Path) -> tuple[str, str]:
        if len(path.parts) == 1:
            return (path.parts[0], "value")
        return (path.parts[0], path.parts[1])

    def _emit_value(self, value: Any) -> str:
        if isinstance(value, DurationLit):
            return f"logos_duration({value.to_seconds()})"
        elif isinstance(value, bool):
            return f"logos_int({1 if value else 0})"
        elif isinstance(value, int):
            return f"logos_int({value})"
        elif isinstance(value, float):
            return f"logos_float({value})"
        elif isinstance(value, str):
            return f'logos_string("{_esc(value)}")'
        elif isinstance(value, (SetLit, ListLit)):
            raise CompilationError("SetLit/ListLit not supported in compiled mode")
        elif isinstance(value, ArithExpr):
            raise CompilationError("ArithExpr not supported in compiled mode")
        else:
            return f'logos_string("{_esc(str(value))}")'

    def _get_confidence(self, b: SemanticBinding) -> str:
        ann = b.annotations
        if ann and ann.confidence:
            raw = ann.confidence.raw
            if raw == "absolute":
                return "1.0"
            elif isinstance(raw, (int, float)):
                return str(float(raw))
            elif isinstance(raw, tuple):
                return str(float((raw[0] + raw[1]) / 2.0))
        return "1.0"

    # ── main() ────────────────────────────────────────────────────────────────

    def _emit_main(self) -> str:
        lines = [
            "int main(void) {",
            "    logos_graph graph = {0};",
            "    logos_env   env   = {0};",
            "    env.graph = &graph;",
            "    logos_setup(&graph);",
            "",
        ]
        for q in self.queries:
            if isinstance(q, BoolQuery):
                lines.extend(self._emit_bool_query(q))
            elif isinstance(q, FindQuery):
                lines.extend(self._emit_find_query(q))
        lines.append("    return 0;")
        lines.append("}")
        return "\n".join(lines)

    # ── BoolQuery emission ────────────────────────────────────────────────────

    def _emit_bool_query(self, q: BoolQuery) -> list[str]:
        pred      = q.predicate.name
        cname     = _c_id(pred)
        args      = q.predicate.args
        arg_exprs = ", ".join(self._query_term(a) for a in args)
        text      = f"{pred}({', '.join(self._query_text_arg(a) for a in args)})"
        return [
            "    {",
            "        int    _found = 0;",
            "        double _conf  = 0.0;",
            "        env.capture_found = &_found;",
            "        env.capture_conf  = &_conf;",
            "        env.confidence    = 1.0;",
            f"        pred_{cname}(&env, {arg_exprs}, k_bool_capture);",
            f'        logos_print_bool_result("{_esc(text)}", _found, _conf);',
            "    }",
        ]

    def _query_term(self, arg: Any) -> str:
        """C expression for a query argument (always concrete)."""
        if isinstance(arg, Path) and len(arg.parts) == 1:
            return f'logos_string("{_esc(arg.parts[0])}")'
        elif isinstance(arg, str):
            return f'logos_string("{_esc(arg)}")'
        elif isinstance(arg, bool):
            return f"logos_int({1 if arg else 0})"
        elif isinstance(arg, int):
            return f"logos_int({arg})"
        elif isinstance(arg, float):
            return f"logos_float({arg})"
        elif isinstance(arg, DurationLit):
            return f"logos_duration({arg.to_seconds()})"
        else:
            return f'logos_string("{_esc(str(arg))}")'

    def _query_text_arg(self, arg: Any) -> str:
        """Human-readable text for a query argument (for the printed label)."""
        if isinstance(arg, Path):
            return str(arg)
        elif isinstance(arg, Variable):
            return arg.name
        else:
            return str(arg)

    # ── FindQuery emission ────────────────────────────────────────────────────

    def _emit_find_query(self, q: FindQuery) -> list[str]:
        """
        Enumerate all unique subjects in the graph and test the predicate
        condition for each.  Handles single and multi-variable find queries
        where variables map 1-to-1 with predicate arguments.
        """
        var_names = [v.name for v in q.variables]

        # Collect the primary predicate call condition
        pred_conds = [c for c in q.conditions if isinstance(c, PredicateCall)]
        if not pred_conds:
            return [
                "    {",
                "        /* find query: no predicate conditions, skipping */",
                "    }",
            ]

        pc    = pred_conds[0]
        cname = _c_id(pc.name)
        nv    = len(var_names)

        # Build per-subject argument expression (replace query vars with _s)
        def arg_expr(a: Any) -> str:
            if isinstance(a, Variable) and a.name in var_names:
                return "logos_string(_s)"
            return self._query_term(a)

        arg_exprs = ", ".join(arg_expr(a) for a in pc.args)

        # C array of variable name strings
        vnames_lit = "{" + ", ".join(f'"{n}"' for n in var_names) + "}"

        # C array of result term values (variable positions filled by _s)
        def val_expr(v: Variable) -> str:
            for a in pc.args:
                if isinstance(a, Variable) and a.name == v.name:
                    return "logos_string(_s)"
            return f'logos_string("{v.name}")'

        vals_lit = "{" + ", ".join(val_expr(v) for v in q.variables) + "}"

        lines = [
            "    {",
            f"        /* find {', '.join(var_names)} where {pc.name}(...) */",
            "        const char *_seen[LOGOS_MAX_FACTS];",
            "        int _nseen = 0, _i, _j;",
            "        memset(_seen, 0, sizeof(_seen));",
            "        for (_i = 0; _i < graph.count; _i++) {",
            "            const char *_s = graph.facts[_i].subject;",
            "            int _dup = 0;",
            "            for (_j = 0; _j < _nseen; _j++)",
            "                if (_seen[_j] == _s) { _dup = 1; break; }",
            "            if (_dup) continue;",
            "            _seen[_nseen++] = _s;",
            "            {",
            "                int    _found = 0;",
            "                double _conf  = 0.0;",
            "                env.capture_found = &_found;",
            "                env.capture_conf  = &_conf;",
            "                env.confidence    = 1.0;",
            f"                pred_{cname}(&env, {arg_exprs}, k_bool_capture);",
            "                if (_found) {",
            f"                    const char *_vnames[{nv}] = {vnames_lit};",
            f"                    logos_term   _vals[{nv}]   = {vals_lit};",
            f"                    logos_print_find_row(_vnames, _vals, {nv}, _conf);",
            "                }",
            "            }",
            "        }",
            "    }",
        ]
        return lines


# ── RuleEmitter ───────────────────────────────────────────────────────────────

class RuleEmitter:
    """Emits one C function for a single InferenceRule clause."""

    def __init__(self, rule: InferenceRule, pred_name: str, idx: int,
                 compiler: Compiler):
        self.rule      = rule
        self.pred_name = pred_name
        self.idx       = idx
        self.compiler  = compiler
        self._ctr      = 0

        # Map from Logos variable name → C variable expression
        self._var_map: dict[str, str] = {}
        for arg in rule.head.args:
            if isinstance(arg, Variable):
                self._var_map[arg.name] = f"var_{_c_id(arg.name)}"

    def _fresh(self) -> int:
        self._ctr += 1
        return self._ctr

    # ── Function skeleton ─────────────────────────────────────────────────────

    def emit(self) -> str:
        cname  = _c_id(self.pred_name)
        params = []
        for arg in self.rule.head.args:
            params.append(f"logos_term var_{self.compiler._head_arg_cname(arg)}")
        param_str = ", ".join(params)

        lines = [
            f"static int rule_{cname}_{self.idx}"
            f"(logos_env *env, {param_str}, logos_cont k) {{",
        ]
        for i, cond in enumerate(self.rule.conditions):
            lines.extend(self._emit_cond(cond, i))

        lines.append("    env->confidence = logos_degrade(env->confidence);")
        lines.append("    return k(env);")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    # ── Condition dispatch ────────────────────────────────────────────────────

    def _emit_cond(self, cond: Any, idx: int) -> list[str]:
        if isinstance(cond, Comparison):
            return self._emit_comparison(cond, idx)
        elif isinstance(cond, PredicateCall):
            return self._emit_pred_call_cond(cond, idx)
        elif isinstance(cond, NegatedPredicate):
            return self._emit_negation(cond, idx)
        else:
            raise CompilationError(
                f"Unsupported condition type in compiled mode: {type(cond).__name__}"
            )

    # ── Comparison condition ──────────────────────────────────────────────────

    def _emit_comparison(self, cond: Comparison, idx: int) -> list[str]:
        left = cond.left
        op   = cond.op
        right = cond.right

        if not (isinstance(left, Path) and len(left.parts) == 2):
            raise CompilationError(
                f"Comparison left side must be a two-part path (e.g. P.age); "
                f"got: {left}"
            )

        subj_part = left.parts[0]
        pred_part = left.parts[1]
        c_subj    = self._resolve_var(subj_part)
        op_num    = _OP_MAP.get(op, 4)
        rhs_expr  = self._resolve_term(right)

        return [
            f"    /* {left} {op} {right} */",
            f"    {{",
            f"        logos_term _val_{idx}; double _conf_{idx};",
            f"        if (!logos_graph_lookup(env->graph,",
            f'                logos_walk(env, {c_subj}).s, "{_esc(pred_part)}",',
            f"                &_val_{idx}, &_conf_{idx})) return 0;",
            f"        logos_term _rhs_{idx} = {rhs_expr};",
            f"        if (!logos_compare(_val_{idx}, {op_num}, _rhs_{idx})) return 0;",
            f"        env->confidence = logos_conjoin(env->confidence, _conf_{idx});",
            f"    }}",
        ]

    # ── Predicate call condition ──────────────────────────────────────────────

    def _emit_pred_call_cond(self, cond: PredicateCall, idx: int) -> list[str]:
        cname     = _c_id(cond.name)
        arg_exprs = ", ".join(self._resolve_term(a) for a in cond.args)
        return [
            f"    /* condition: {cond.name}(...) */",
            f"    {{",
            f"        int    _pc_found_{idx} = 0;",
            f"        double _pc_conf_{idx}  = 0.0;",
            f"        void *_pf_{idx} = env->capture_found;",
            f"        void *_pc_{idx} = env->capture_conf;",
            f"        logos_mark_t _pm_{idx} = logos_mark(env);",
            f"        env->capture_found = &_pc_found_{idx};",
            f"        env->capture_conf  = &_pc_conf_{idx};",
            f"        pred_{cname}(env, {arg_exprs}, k_bool_capture);",
            f"        logos_undo(env, _pm_{idx});",
            f"        env->capture_found = _pf_{idx};",
            f"        env->capture_conf  = _pc_{idx};",
            f"        if (!_pc_found_{idx}) return 0;",
            f"        env->confidence = logos_conjoin(env->confidence, _pc_conf_{idx});",
            f"    }}",
        ]

    # ── Negation-as-failure ───────────────────────────────────────────────────

    def _emit_negation(self, cond: NegatedPredicate, idx: int) -> list[str]:
        pc        = cond.predicate
        cname     = _c_id(pc.name)
        arg_exprs = ", ".join(self._resolve_term(a) for a in pc.args)
        return [
            f"    /* not {pc.name}(...) — negation-as-failure */",
            f"    {{",
            f"        int    _naf_found_{idx} = 0;",
            f"        double _naf_conf_{idx}  = 0.0;",
            f"        void *_pf_{idx} = env->capture_found;",
            f"        void *_pc_{idx} = env->capture_conf;",
            f"        logos_mark_t _nm_{idx} = logos_mark(env);",
            f"        env->capture_found = &_naf_found_{idx};",
            f"        env->capture_conf  = &_naf_conf_{idx};",
            f"        pred_{cname}(env, {arg_exprs}, k_bool_capture);",
            f"        logos_undo(env, _nm_{idx});",
            f"        env->capture_found = _pf_{idx};",
            f"        env->capture_conf  = _pc_{idx};",
            f"        if (_naf_found_{idx}) return 0;  /* NAF: fail if proved */",
            f"    }}",
        ]

    # ── Term resolution ───────────────────────────────────────────────────────

    def _resolve_var(self, name: str) -> str:
        """C expression for a subject variable (rule parameter)."""
        if name in self._var_map:
            return self._var_map[name]
        # Literal subject name or path root not listed as Variable
        return f"var_{_c_id(name)}"

    def _resolve_term(self, term: Any) -> str:
        """C expression producing a logos_term for the given AST node."""
        if isinstance(term, Variable):
            return self._resolve_var(term.name)
        elif isinstance(term, Path):
            if len(term.parts) == 1:
                name = term.parts[0]
                # Uppercase single-part path treated as variable
                if name[0].isupper() and name in self._var_map:
                    return self._var_map[name]
                return f'logos_string("{_esc(name)}")'
            else:
                raise CompilationError(
                    f"Multi-part path {term} used as a term (not a lookup target) "
                    f"— this is not supported in compiled mode"
                )
        elif isinstance(term, bool):
            return f"logos_int({1 if term else 0})"
        elif isinstance(term, int):
            return f"logos_int({term})"
        elif isinstance(term, float):
            return f"logos_float({term})"
        elif isinstance(term, str):
            return f'logos_string("{_esc(term)}")'
        elif isinstance(term, DurationLit):
            return f"logos_duration({term.to_seconds()})"
        else:
            raise CompilationError(
                f"Unsupported term type in compiled mode: "
                f"{type(term).__name__}: {term!r}"
            )
